version: "3.8"

services:
  web:
    build: ./src/
    command: uvicorn src.main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRESS_DB_USER}:${POSTGRESS_DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}
    restart: always
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRESS_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRESS_DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

volumes:
  postgres_data:

  